main: thirtyvirus.template.WorldOfBlocks
version: 1.0
name: WorldOfBlocks
api-version: 1.13

commands:
  wob:
    description: Main command for WorldOfBlocks. Use /wob help for more info
permissions:
  wob.user:
    description: Allows player to use the plugin's user features
    default: true
  wob.admin:
    description: Allows player to use the plugin's admin features
    default: op